### ISSUE TITLE
Error: Function setSelectionRanges not found in RStudio

### ISSUE THREAD

**Issue by happyshows** [sfr/RStudio-Addin-Snippets#2]
When I try to utilize any function, it always show this error:
Error: Function setSelectionRanges not found in RStudio

I'm using latest Rstudio on WINDOWS

**Comment by sfr** [comment]
You need to download the [preview version of RStudio](https://www.rstudio.com/products/rstudio/download/preview/).

Also you will need to install [latest rstudioapi](https://github.com/rstudio/rstudioapi) package from github.

``` r
install_github('rstudio/rstudioapi')
```
